development:
  adapter: postgresql
  database: sc2games_chart_development
  pool: 5

test:
  adapter: postgresql
  database: sc2games_chart_production
  pool: 5

test:
  adapter: postgresql
  production: sc2games_chart_production
  pool: 5
